name: 'Z64 Packer Release Assets'
description: 'Action for releasing necessary assets for repository compatibility with Z64 Music Packer'
inputs:
  name:
    description: 'Name of the music repository'
    required: true
  description:
    description: 'Description for the music repository'
    required: false
    default: ''
  binaries-path:
    description: 'Local path to the music files'
    required: false
    default: 'binaries/'
  previews-path:
    description: 'Local path to the preview files'
    required: false
    default: 'previews/'
  avatar-url:
    description: 'URL for an image to use as the repository avatar'
    required: false
    default: 'https://github.githubassets.com/images/gravatars/gravatar-user-420.png?size=32'
  metadata-spreadsheet:
    description: 'URL for a Google Docs Spreadsheet with metadata (currently only used for DJs repos, in their format)'
    required: false
    default: ''
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Download current release files if there is any
      uses: robinraju/release-downloader@v1.12
      with:
        tag: 'z64packer'
        latest: true
        fileName: '*'
        out-file-path: 'z64packer'
        
    - name: Copy scripts and show results
      run: |
        cp -r $GITHUB_ACTION_PATH/src/* z64packer/
        jq --null-input \
          --arg name "$INPUT_NAME" \
          --arg description "$INPUT_DESCRIPTION" \
          --arg binaries "$INPUT_BINARIES" \
          --arg previews "$INPUT_PREVIEWS" \
          --arg avatarUrl "$INPUT_AVATAR_URL" \
          '$ARGS.named' > z64packer/z64musicpacker.properties
        ls -R
        head z64packer/z64musicpacker.properties
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
        INPUT_BINARIES: ${{ inputs.binaries-path }}
        INPUT_PREVIEWS: ${{ inputs.previews-path }}
        INPUT_AVATAR_URL: ${{ inputs.avatar-url }}
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "z64packer/z64_python_requirements.txt"

    - name: Run database fixer
      run: python "z64packer/z64_database_fixer.py" --ci
      shell: bash
    
    - name: Extract metadata from datasheet if there is any
      if: ${{ github.event.inputs.metadata-spreadsheet != '' }}
      run: python "z64packer/z64_dj_datasheet_tool.py" --ci
      shell: bash

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          z64packer/binaries.zip
          z64packer/z64games.json
          z64packer/z64songs.json
          z64packer/z64musicpacker.properties
        tag_name: z64packer
        name: Z64 Packer Assets
        draft: false
        prerelease: false
